# Generated by Django 3.2.8 on 2021-11-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uslugi', '0002_auto_20211118_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('contacts', models.CharField(max_length=150)),
                ('text', models.TextField(max_length=1500)),
            ],
        ),
    ]
