# Generated by Django 3.2.8 on 2021-11-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsbig',
            name='type',
            field=models.CharField(default='Общие вопросы', max_length=200),
            preserve_default=False,
        ),
    ]
