# Generated by Django 3.2.8 on 2021-11-08 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211021_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='otzyv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.CharField(max_length=50)),
                ('time', models.DateTimeField()),
                ('data', models.TextField(max_length=300)),
            ],
        ),
    ]
