# Generated by Django 3.2.8 on 2021-11-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_otzyv_showed'),
    ]

    operations = [
        migrations.CreateModel(
            name='uslugi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100)),
                ('data', models.TextField()),
                ('image', models.ImageField(upload_to='img')),
            ],
        ),
    ]
