# Generated by Django 3.2.8 on 2021-11-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_uslugi'),
    ]

    operations = [
        migrations.AddField(
            model_name='uslugi',
            name='showed',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
