# Generated by Django 3.2.8 on 2021-11-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_uslugi_showed'),
    ]

    operations = [
        migrations.AddField(
            model_name='uslugi',
            name='type',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
