# Generated by Django 3.2.8 on 2021-11-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_uslugi_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uslugi',
            name='data',
            field=models.TextField(max_length=300),
        ),
    ]
