# Generated by Django 3.2.8 on 2021-11-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_uslugi_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uslugi',
            name='image',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
