# Generated by Django 3.2.8 on 2021-11-09 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_uslugi_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uslugi',
            name='image',
        ),
    ]
